### ISSUE TITLE
ChoroQ HG 3 support

### ISSUE THREAD

**Issue by mholeys** [mholeys/roadtrip-choroq-tools#4]
The current state of support, is accidental.
The following should extract if only partially:
- Course mesh
- Course textures
- Car textures

Plan is to support both games, as they share (with variation) the same file format, due to being made by E-game. inc (www.e-game.co.jp).

**Comment by mholeys** [comment]
There is now a ChoroQ HG 3 car file, that should extract the cars correctly, along with additional parts, and the frogs, which are in the CARS folder. 

https://github.com/mholeys/roadtrip-choroq-tools/commit/efa119c50f2d975d53bf850151e86c8fe58d18db

**Comment by Facepalm38** [comment]
Seems to give this error when trying to fetch the cars

``` Traceback (most recent call last):
  File "D:\CQExports\CQExtract\car-extractor.py", line 88, in <module>
    if gameVersion != 2 and gameVersion != 3:
       ^^^^^^^^^^^
NameError: name 'gameVersion' is not defined

**Comment by Facepalm38** [comment]
Ah, turns out I needed to give an extra input third input, oops! Disregard the previous comment.

Courses seem to partially export, which is fine. I'm once again testing the JP version, to make sure it still works between game builds.
So far all cars, items and cosmetics seem to export correctly!

**Comment by Facepalm38** [comment]
Seems when trying to export with PLY though, it doesn't like that. Happens right after the FASHION folder is exported, so the FROG breaks it

```Traceback (most recent call last):
  File "D:\CQExports\CQExtract\car-extractor.py", line 102, in <module>
    process_file(entry, folderOut, obj, ply, gameVersion)
  File "D:\CQExports\CQExtract\car-extractor.py", line 54, in process_file
    mesh.writeMeshToPly(fout)
  File "D:\CQExports\CQExtract\choroq\car_hg3.py", line 394, in writeMeshToPly
    nx = '{:.20f}'.format(self.meshNormals[i][0])
                          ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by mholeys** [comment]
I only took a quick look at this, I missed some bits in the car extractor, I have updated this now. The game version should have been optional.

**Comment by mholeys** [comment]
These issues should be fixed now, the normals were not being added, and the game version did not have a default.

The following should also now work:
- ChoroQ HG3:
  - Course meshes (Cxxx files)
  - Course maps (Cxxx files) (currently broken up)
  - Cars/Objects
  - The Axxx files

Bits within the courses: e.g doors/fish are extracted as course meshes and might not be correct, it might be possible to extract these into thier own files. 

C17: Noise City
C16: Echo Forest
C15: Scratch Mountain
C14: Grunge Garden

**Comment by mholeys** [comment]
Currently supported (since 94c5da809e5a06404c51d240faf2dce949e59dcc)

- HG3 Courses (all as far I have tested)
    - Meshes
    - Textures
    - Link between meshes and textures
    - Colliders
    - Extra objects
